import './global.css'
import Head from 'next/head';



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Head>
      <title>ASL Learning</title>
      <meta name="description" content="Learn Sign language by playing games" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>

      <body>{children}</body>
      
    </html>
  )
}
